# Generated by Django 2.1.2 on 2018-10-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.CharField(max_length=50, verbose_name='adsoyad'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content2',
            field=models.CharField(max_length=50, verbose_name='mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content3',
            field=models.CharField(max_length=20, verbose_name='tel'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='oluşturulma Tarihi'),
        ),
    ]
