# Generated by Django 2.1.2 on 2018-10-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image', verbose_name='Resim Ekle'),
        ),
    ]
